CONTEXT = {
    "fr": (
        "<strong>Contexte – Accord FATCA</strong><br><br>"
        "Par un arrêt interlocutoire rendu fin 2025, la Cour des marchés de Belgique a décidé de saisir "
        "la Cour de justice de l’Union européenne (CJUE) de treize questions préjudicielles "
        "relatives à la conformité de l’accord intergouvernemental FATCA avec le droit de "
        "l’Union européenne, et en particulier avec les exigences du règlement général sur "
        "la protection des données (RGPD).<br><br>"
        "Cette saisine intervient à la suite de la décision n°79/2025 du 24 avril 2025 de "
        "l’Autorité de protection des données (APD), par laquelle plusieurs violations du "
        "RGPD ont été constatées. Cette décision impose au SPF Finances, en tant que "
        "responsable de traitement, de mettre en conformité les transferts de données "
        "opérés dans le cadre de l’accord FATCA afin de les rendre compatibles avec le RGPD.<br><br>"
        "Dans ce contexte juridique désormais porté au niveau européen, les personnes "
        "concernées par l’accord FATCA disposent du droit de demander l’effacement de leurs "
        "données à caractère personnel lorsqu’elles estiment que leur traitement ne respecte "
        "pas le RGPD.<br><br>"
        "La présente démarche a pour objet de vous permettre d’exercer concrètement ce "
        "droit à l’effacement auprès du SPF Finances (l’administration fiscale belge), "
        "en générant un courrier prêt à être imprimé, signé et adressé."
    ),
    "nl": (
        "<strong>Context – FATCA-akkoord</strong><br><br>"
        "Bij een interlocutoir arrest dat eind 2025 werd gewezen, heeft het Marktenhof van België "
        "beslist om dertien prejudiciële vragen voor te leggen aan het Hof van Justitie van "
        "de Europese Unie (HvJ-EU) met betrekking tot de verenigbaarheid van het "
        "intergouvernementele FATCA-akkoord met het recht van de Europese Unie, en in het "
        "bijzonder met de vereisten van de Algemene Verordening Gegevensbescherming (AVG).<br><br>"
        "Deze verwijzing volgt op beslissing nr. 79/2025 van 24 april 2025 van de "
        "Gegevensbeschermingsautoriteit (GBA), waarin meerdere schendingen van de AVG werden "
        "vastgesteld. In deze beslissing wordt de FOD Financiën, in zijn hoedanigheid van "
        "verwerkingsverantwoordelijke, verplicht om de gegevensoverdrachten die plaatsvinden "
        "in het kader van het FATCA-akkoord in overeenstemming te brengen met de AVG.<br><br>"
        "In deze juridische context, die inmiddels op Europees niveau wordt behandeld, "
        "beschikken personen die door het FATCA-akkoord worden getroffen over het recht om "
        "de wissing van hun persoonsgegevens te verzoeken wanneer zij van oordeel zijn dat "
        "de verwerking ervan niet in overeenstemming is met de AVG.<br><br>"
        "Het doel van deze démarche is u in staat te stellen dit recht op gegevenswissing "
        "concreet uit te oefenen ten aanzien van de FOD Financiën (de Belgische "
        "belastingadministratie), door het genereren van een brief die kan worden afgedrukt, "
        "ondertekend en verzonden."
    ),
}
